[project]
name = "test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.115.14",
    "hloc",
    "websockets>=15.0.1",
]

[tool.uv.sources]
hloc = { path = "Hierarchical-Localization" }
